# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
on:
  push:
    branches: [ main ]
  pull_request:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    permissions:
      checks: write
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # do a matrix test with different node versions
    strategy:
      fail-fast: false
      matrix:
        node-version: [ lts/*]
        #can't test on 5.6.42 because database is too up-to-date ( 5.12.72 )
        unifi-version: [ latest]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: prepare
          path: .
      # try to perform a nodejs setup
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build, and test
        run: |
          npm install
          npm run build
          echo start tests
          npm run test:CI:coverage
      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: ./coverage
